[template]
src = "bird.cfg.template"
dest = "/config/bird.cfg"
prefix = "/calico/bgp/v1"
keys = ["/rr_v4", "/global", "/host", "/ospf_to_hosts"]
check_cmd = "bird -p -c {{.src}}"
reload_cmd = "pkill -HUP bird || true"
